baseurl = "https://yenngee-dataviz.netlify.app/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Data Visualization"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

enableRobotsTXT = true

[params]
  background = "#f7f7f7"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  backgroundDark = "#333"
  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  # dark404 = true

  author = "Ng Yen Ngee"
  # description = ""
  avatar = "/img/avatar.jpeg"
  headerTitle = "Data Visualization"
  motto = "Analyse data to make better decisions"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "ngyenngee@hotmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  linkedin = "https://www.linkedin.com/in/ng-yen-ngee/"
  github = "https://github.com/yenngee"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = false

  [params.advanced]
    customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
